const savedDownloadedUrlBox = "downloadedData";
const browsingHistoryBox = "browsingHistoryBox";
const shortcutsBox = "shortcutBox";
const timeUsageBox = "timeUsageBox";
const backendComputedTimeBox = "backendComputedTimeBox";

class AppStrings {
  static const noRouteFound = "No Route Found";
  static const back = "Back";
  static const skip = "Skip";
  static const clickToContinue = "Continue";
  static const finish = "FINISH";
  static const welcome = "Welcome";
  static const loginBack = "Login in back to your account.";
  static const userNameOrEmail = "Username or Email";
  static const password = "Password";
  static const forgotPassword = "Forgot Password?";
  static const login = "login";
  static const donHaveAnAccount = "Don’t Have An Account?";
  static const signUp = "Sign Up";
  static const createYourEvsAccount = "Create your EVSpay account.";
  static const userName = "Username";
  static const email = "Email";
  static const firstName = "First Name";
  static const lastName = "Last Name";
  static const middleName = "Middle Name";
  static const confirmPassword = "Confirm Password";
  static const alreadyHaveAnAccount = "Already Have An Account?";
  static const signIn = "Sign In";
  static const setUpTransactionPin = "Setup Transaction Pin";
  static const setUpPinForApp = "Setup pin for app login and transactions";
  static const pin = "PIN";
  static const confirmPin = "Confirm Pin";
  static const confirmPinForApp = "Confirm  pin for app login and transactions";
  static const verifyYourEmail = "Verify your email";
  static const enterTheCode = "Please enter the code sent to email@demo.com";
  static const confirmationCode = "Confirmation code";
  static const verifyAccount = "Verify Account";
  static const recoverMyPassword = "Recover my password";
  static const enterTheEmailAddress =
      "Enter the email address for your Evs Pay account and we will send a reset link to your inbox. Follow the link to reset your password.";
  static const settings = "Settings";
  static const security = "Security";
  static const notifications = "Notifications";
  static const transactions = "Transactions";
  static const verification = "Verification";
  static const profile = "Profile";
  static const proceedToSell = "Proceed to sell";
  static const proceedToBuy = "Proceed to buy";
  static const termsPfService = "Terms of service";
  static const about = "About";
  static const signOut = "Sign Out";
  static const securitySettings = "Security Settings";
  static const twoFactorAuth = "Two-factor Authentication";
  static const with2StepVerification =
      "With 2-Step Verification, you'll protect your account with both your password and your phone.";
  static const changePassword = "Change Password";
  static const receiveNotificationOfNew =
      "Receive notifications of new online payments in your advertisements.";
  static const allowBioMetrics = "Allow bio metrics ";
  static const receiveNotificationOfNewRelease =
      "Receive notifications of new online escrow releases.";
  static const changePin = "Change Pin";
  static const changeTransactionPin = "Change transaction Pin";
  static const notificationSettings = "Notification Settings";
  static const newTradeRequest = "New trade request";
  static const receiveNotificationOfNewTrade =
      "Receive notifications of new trade requests.";
  static const newDisputes = "New disputes";
  static const receiveNotificationsOfNewDisputes = "New disputes";
  static const newOnlinePayment = "New online payments";
  static const receiveNotificationsOfNewOnlinePayments =
      "Change your password.";
  static const onlineEscrowRelease = "Online escrow released";
  static const receiveNotificationsOfNewOnlineEscrowReleases =
      "Receive notifications of new online escrow releases.";
  static const notification = "Notification";
  static const profileEdit = "Profile edit";
  static const tapOnTheImageToChangeProfilePicture =
      "Tap on the image to change the profile picture ";
  static const name = "Name";
  static const ngn = "NGN";
  static const phone = "Phone";
  static const saveChanges = "Save Changes";
  static const areousEmail = "areous@evspay.com";
  static const areous = "areous";
  static const phoneNumber = "+1 255 699996 588";
  static const identityVerification = "Identitiy verification ";
  static const proveYouAreInNigeria = "Prove you live in Nigeria";
  static const nationality = "Nationality";
  static const emailVerification = "Email Verification";
  static const aUtilityBillToProof = "A utility bill to proof your address";
  static const phoneNumberVerification = "Phone Number ";
  static const address = "Address";
  static const identityCard = "Identity Card";
  static const snapShot = "Snap Shot";
  static const proofOfAddress = "Proof Of Address";
  static const paymentMethod = "Payment Method";
  static const selectCoin = "Select Coin";
  static const uploadEitherCable =
      "Upload either Cable TV bill such as DSTV bill or Utility bill for services to the address.";
  static const uploadYourID = "Upload your ID ";
  static const uploadEitherYourPassport =
      "Upload either your passport, driver’s licence or other national ID. ";
  static const upload = "Upload";
  static const takeAShot = "Snap shot";
  static const youWouldHaveToTake =
      "You would have to take a selfie for verification of your identity";
  static const frontOfCard = "Front of card";
  static const positionAll4CornersOf =
      "Position all 4 corners of the front clearly in the frame and remove any over";
  static const submitted = "Submitted";
  static const verifyPhone = "Verify Your Phone";
  static const enterTheEmail =
      "Enter the email address for your Evs Pay account and we will send a reset link to your inbox. Follow the link to reset your password.";
  static const resendVerification = "Resend Verification ";
  static const issuedInYourCountry = "Issued in your country";
  static const sendALivePicture = "Send a live picture of yourself";
  static const verify = "Verify";
  static const wallet = "Wallet";
  static const walletBalance = "Wallet Balance";
  static const amount = "\$23,000.90 ";
  static const bitCoinAmount = "0.27398663 BTC";
  static const send = "Send";
  static const receive = "Receive";
  static const trade = "Trade";
  static const tradeTimeLimit = "Trade Time Limit ";
  static const transactionHistory = "Transactions History";
  static const waiting = "Waiting";
  static const home = "Home";
  static const trades = "Trades";
  static const pending = "Pending";
  static const completed = "Completed";
  static const cancelled = "Cancelled";
  static const youHaveNotComplete =
      "You have to complete your Verification to trade";
  static const sell = "SELL";
  static const buy = "BUY";
  static const buyNow = "Buy Now";
  static const sellLowerCase = "Sell";
  static const buyLowerCase = "Buy";
  static const sellersRate = "Seller's Rate";
  static const buyLimit = "Buy Limit";
  static const iWantToBuyBtc = "I want to buy BTC";
  static const iWillReceive = "I will receive  ";
  static const aboutThisOffer = "About this offer";
  static const terms = "Terms";
  static const termsLimit = "Trade Time Limit ";
  static const six20N = "620 NGN";
  static const oneK = "1000 NGN";
  static const perUSD = "per USD";
  static const search = "Search";
  static const recipientBtcAddress = "Recipient’s BTC  Address";
  static const walletAddress = "Wallet Address ";
  static const scanQrCode = "Scan QR Code";
  static const descriptionOptional = "Description (Optional)";
  static const btc = "BTC";
  static const usd = "USD";
  static const scanThisQrCode = "Scan this QR Code Receive Bitcoin ";
  static const walletID = "3FUNYpHdGFLE7smoMCwZWHTab4zwwW9jrS";
  static const copyAddressToClipboard = "Copy address to clipboard";
  static const saveQrCode = "Save QR Code";
  static const transactionPin = "Transaction pin";
  static const enterPinToCompleteTransaction =
      "Enter PIN to complete transaction ";
  static const amt = "Amount";
  static const close = "Close";
  static const myAds = "My Ads";
  static const enableTrade = "Enable Trade";
  static const disableTrade = "Disable Trade";
  static const cancel = "Cancel";
  static const editThisTrade = "Edit this trade";
  static const viewTrade = "View trade";
  static const deleteTrade = "Delete trade";
  static const myOfferDetails = "My Offer Details";
  static const tradesForOffer = "Trades for offer";
  static const createAnOffer = "Create an Offer";
  static const updateAnOffer = "Update an Offer";
  static const editOffer = "Edit Offer";
  static const buyBitcoin = "Buy Bitcoin";
  static const sellBitcoin = "Sell Bitcoin";
  static const inputLocation = "Input location ";
  static const location = "Location:";
  static const howMuchDoYou = "How much do you want to sell ?";
  static const howMuchDoYouWantToBuy = "How much do you want to buy?";
  static const startTyping = "Start typing.. ";
  static const showAll = "Show all";
  static const rate = "Rate:";
  static const andReceive = "And receive";
  static const iWantToSell = "I want to sell my BTC";
  static const iWantToPayWithItunes = "I will pay with iTunes Gift Card";
  static const maximum = "Maximum";
  static const minimum = "Minimum";
  static const eight000 = "800,0000";
  static const ten000000 = "10,000,000";
  static const termsOfTrade = "Terms of Trade";
  static const createOffer = "Create Offer";
  static const active = "Active";
  static const confirmed = "Confirmed";
  static const disputed = "Disputed";
  static const allFieldsRequired = "All fields are required";
  static const passwordMismatch = "All fields are required";
  static const emailVerified = "Email Verified";
  static const phoneVerified = "Phone number Verified";
  static const addressVerified = "Address Verified";
  static const idVerified = "ID Verified";
  static const selfieVerified = "Selfie Verified";
  static const fillAllRequiredFields = "Fill all required fields";
  static const specifyAmountToSell = "Specify Amount To Sell";
  static const buyer = "buyer";
  static const youHaveNotCreatedAnyOffer =
      "You have not created any offers yet";
  static const youHaveNoTrade = "You have no trade yet";
  static const secureEscrow = "Secure escrow + Automated trade with";
  static const transferFundsTo =
      "Transfer funds to your wallet address to start trading.";
  static const transferFundsToYourWallet =
      "Transfer funds to your wallet address to get started.";
}
