
import 'package:evs_pay_mobile/resources/image_manager.dart';

class TradeModel{
  final String buyerName;
  final String status;
  final String amount;
  final String time;
  final String type;
  final String paymentMethod;

  TradeModel({
    required this.buyerName,
    required this.status,
    required this.amount,
    required this.time,
    required this.type,
    required this.paymentMethod,
  });

}

final List<TradeModel> trades = [
  TradeModel(buyerName: AppImages.emmanuelPraise,
      type: "Sell", status: "Active",
      amount: "800,000  NGN", time: "12th Jul, 2022 - 12:12 AM",
    paymentMethod: "Bank Transfer"
  ),
  TradeModel(buyerName: AppImages.johnDoe,
      type: "Buy", status: "Active",
      amount: "800,000  NGN", time: "12th Jul, 2022 - 12:12 AM",
      paymentMethod: "Bank Transfer"),
  TradeModel(buyerName: AppImages.emmanuelPraise,
      type: "Sell", status: "Active",
      amount: "800,000  NGN", time: "12th Jul, 2022 - 12:12 AM",
      paymentMethod: "Bank Transfer"),
  TradeModel(buyerName: AppImages.emmanuelPraise,
      type: "Sell", status: "Active",
      amount: "800,000  NGN", time: "12th Jul, 2022 - 12:12 AM",
      paymentMethod: "Bank Transfer"),
  TradeModel(buyerName: AppImages.emmanuelPraise,
      type: "Sell", status: "Active",
      amount: "800,000  NGN", time: "12th Jul, 2022 - 12:12 AM",
      paymentMethod: "Bank Transfer"),
  TradeModel(buyerName: AppImages.johnDoe,
      type: "Sell", status: "Active",
      amount: "800,000  NGN", time: "12th Jul, 2022 - 12:12 AM",
      paymentMethod: "Bank Transfer"),
  TradeModel(buyerName: AppImages.johnDoe,
      type: "Sell", status: "Active",
      amount: "800,000  NGN", time: "12th Jul, 2022 - 12:12 AM",
      paymentMethod: "Bank Transfer"),
  TradeModel(buyerName: AppImages.emmanuelPraise,
      type: "Buy", status: "Active",
      amount: "800,000  NGN", time: "12th Jul, 2022 - 12:12 AM",
      paymentMethod: "Bank Transfer"),
  TradeModel(buyerName: AppImages.emmanuelPraise,
      type: "Buy", status: "Active",
      amount: "800,000  NGN", time: "12th Jul, 2022 - 12:12 AM",
      paymentMethod: "Bank Transfer"),
  TradeModel(buyerName: AppImages.emmanuelPraise,
      type: "Buy", status: "Active",
      amount: "800,000  NGN", time: "12th Jul, 2022 - 12:12 AM",
      paymentMethod: "Bank Transfer"),
  TradeModel(buyerName: AppImages.emmanuelPraise,
      type: "Sell", status: "Active",
      amount: "800,000  NGN", time: "12th Jul, 2022 - 12:12 AM",
      paymentMethod: "Bank Transfer"),
  TradeModel(buyerName: AppImages.johnDoe,
      type: "Sell", status: "Active",
      amount: "800,000  NGN", time: "12th Jul, 2022 - 12:12 AM",
      paymentMethod: "Bank Transfer"),
  TradeModel(buyerName: AppImages.emmanuelPraise,
      type: "Sell", status: "Active",
      amount: "800,000  NGN", time: "12th Jul, 2022 - 12:12 AM",
      paymentMethod: "Bank Transfer"),
  TradeModel(buyerName: AppImages.emmanuelPraise,
      type: "Sell", status: "Active",
      amount: "800,000  NGN", time: "12th Jul, 2022 - 12:12 AM",
      paymentMethod: "Bank Transfer"),
  TradeModel(buyerName: AppImages.emmanuelPraise,
      type: "Sell", status: "Active",
      amount: "800,000  NGN", time: "12th Jul, 2022 - 12:12 AM",
      paymentMethod: "Bank Transfer"),
  TradeModel(buyerName: AppImages.johnDoe,
      type: "Buy", status: "Active",
      amount: "800,000  NGN", time: "12th Jul, 2022 - 12:12 AM",
      paymentMethod: "Bank Transfer"),
  TradeModel(buyerName: AppImages.emmanuelPraise,
      type: "Buy", status: "Active",
      amount: "800,000  NGN", time: "12th Jul, 2022 - 12:12 AM",
      paymentMethod: "Bank Transfer"),
  TradeModel(buyerName: AppImages.emmanuelPraise,
      type: "Sell", status: "Active",
      amount: "800,000  NGN", time: "12th Jul, 2022 - 12:12 AM",
      paymentMethod: "Bank Transfer"),
  TradeModel(buyerName: AppImages.emmanuelPraise,
      type: "Sell", status: "Active",
      amount: "800,000  NGN", time: "12th Jul, 2022 - 12:12 AM",
      paymentMethod: "Bank Transfer"),
  TradeModel(buyerName: AppImages.emmanuelPraise,
      type: "Sell", status: "Active",
      amount: "800,000  NGN", time: "12th Jul, 2022 - 12:12 AM",
      paymentMethod: "Bank Transfer"),
  TradeModel(buyerName: AppImages.johnDoe,
      type: "Sell", status: "Active",
      amount: "800,000  NGN", time: "12th Jul, 2022 - 12:12 AM",
      paymentMethod: "Bank Transfer"),
  TradeModel(buyerName: AppImages.johnDoe,
      type: "Sell", status: "Active",
      amount: "800,000  NGN", time: "12th Jul, 2022 - 12:12 AM",
      paymentMethod: "Bank Transfer"),
  TradeModel(buyerName: AppImages.emmanuelPraise,
      type: "Sell", status: "Active",
      amount: "800,000  NGN", time: "12th Jul, 2022 - 12:12 AM",
      paymentMethod: "Bank Transfer"),
  TradeModel(buyerName: AppImages.emmanuelPraise,
      type: "Sell", status: "Active",
      amount: "800,000  NGN", time: "12th Jul, 2022 - 12:12 AM",
      paymentMethod: "Bank Transfer"),
  TradeModel(buyerName: AppImages.johnDoe,
      type: "Sell", status: "Active",
      amount: "800,000  NGN", time: "12th Jul, 2022 - 12:12 AM",
      paymentMethod: "Bank Transfer"),
  TradeModel(buyerName: AppImages.emmanuelPraise,
      type: "Buy", status: "Active",
      amount: "800,000  NGN", time: "12th Jul, 2022 - 12:12 AM",
      paymentMethod: "Bank Transfer"),
  TradeModel(buyerName: AppImages.emmanuelPraise,
      type: "Sell", status: "Active",
      amount: "800,000  NGN", time: "12th Jul, 2022 - 12:12 AM",
      paymentMethod: "Bank Transfer"),
  TradeModel(buyerName: AppImages.johnDoe,
      type: "Buy", status: "Active",
      amount: "800,000  NGN", time: "12th Jul, 2022 - 12:12 AM",
      paymentMethod: "Bank Transfer"),
];