
import 'package:evs_pay_mobile/resources/image_manager.dart';
import 'package:evs_pay_mobile/resources/strings_manager.dart';

class TradeModel{
  final String buyerName;
  final String status;
  final String coinValue;
  final String time;
  final String type;

  TradeModel({
    required this.buyerName,
    required this.status,
    required this.coinValue,
    required this.time,
    required this.type,
  });

}

final List<TradeModel> trades = [
  TradeModel(buyerName: AppImages.emmanuelPraise,
      type: "Sell", status: AppStrings.waiting,
      coinValue: "0.002BTC", time: "1:23 PM"),
  TradeModel(buyerName: AppImages.johnDoe,
      type: "Buy", status: AppStrings.waiting,
      coinValue: "0.002BTC", time: "1:23 PM"),
  TradeModel(buyerName: AppImages.emmanuelPraise,
      type: "sell", status: AppStrings.waiting,
      coinValue: "0.002BTC", time: "1:23 PM"),
  TradeModel(buyerName: AppImages.emmanuelPraise,
      type: "sell", status: AppStrings.waiting,
      coinValue: "0.002BTC", time: "1:23 PM"),
  TradeModel(buyerName: AppImages.emmanuelPraise,
      type: "sell", status: AppStrings.waiting,
      coinValue: "0.002BTC", time: "1:23 PM"),
  TradeModel(buyerName: AppImages.johnDoe,
      type: "sell", status: AppStrings.waiting,
      coinValue: "0.002BTC", time: "1:23 PM"),
  TradeModel(buyerName: AppImages.johnDoe,
      type: "sell", status: AppStrings.waiting,
      coinValue: "0.002BTC", time: "1:23 PM"),
  TradeModel(buyerName: AppImages.emmanuelPraise,
      type: "Buy", status: AppStrings.waiting,
      coinValue: "0.002BTC", time: "1:23 PM"),
  TradeModel(buyerName: AppImages.emmanuelPraise,
      type: "Buy", status: AppStrings.waiting,
      coinValue: "0.002BTC", time: "1:23 PM"),
  TradeModel(buyerName: AppImages.emmanuelPraise,
      type: "Buy", status: AppStrings.waiting,
      coinValue: "0.002BTC", time: "1:23 PM"),
  TradeModel(buyerName: AppImages.emmanuelPraise,
      type: "sell", status: AppStrings.waiting,
      coinValue: "0.002BTC", time: "1:23 PM"),
  TradeModel(buyerName: AppImages.johnDoe,
      type: "sell", status: AppStrings.waiting,
      coinValue: "0.002BTC", time: "1:23 PM"),
  TradeModel(buyerName: AppImages.emmanuelPraise,
      type: "sell", status: AppStrings.waiting,
      coinValue: "0.002BTC", time: "1:23 PM"),
  TradeModel(buyerName: AppImages.emmanuelPraise,
      type: "sell", status: AppStrings.waiting,
      coinValue: "0.002BTC", time: "1:23 PM"),
  TradeModel(buyerName: AppImages.emmanuelPraise,
      type: "sell", status: AppStrings.waiting,
      coinValue: "0.002BTC", time: "1:23 PM"),
  TradeModel(buyerName: AppImages.johnDoe,
      type: "Buy", status: AppStrings.waiting,
      coinValue: "0.002BTC", time: "1:23 PM"),
  TradeModel(buyerName: AppImages.emmanuelPraise,
      type: "Buy", status: AppStrings.waiting,
      coinValue: "0.002BTC", time: "1:23 PM"),
  TradeModel(buyerName: AppImages.emmanuelPraise,
      type: "sell", status: AppStrings.waiting,
      coinValue: "0.002BTC", time: "1:23 PM"),
  TradeModel(buyerName: AppImages.emmanuelPraise,
      type: "sell", status: AppStrings.waiting,
      coinValue: "0.002BTC", time: "1:23 PM"),
  TradeModel(buyerName: AppImages.emmanuelPraise,
      type: "sell", status: AppStrings.waiting,
      coinValue: "0.002BTC", time: "1:23 PM"),
  TradeModel(buyerName: AppImages.johnDoe,
      type: "sell", status: AppStrings.waiting,
      coinValue: "0.002BTC", time: "1:23 PM"),
  TradeModel(buyerName: AppImages.johnDoe,
      type: "sell", status: AppStrings.waiting,
      coinValue: "0.002BTC", time: "1:23 PM"),
  TradeModel(buyerName: AppImages.emmanuelPraise,
      type: "sell", status: AppStrings.waiting,
      coinValue: "0.002BTC", time: "1:23 PM"),
  TradeModel(buyerName: AppImages.emmanuelPraise,
      type: "sell", status: AppStrings.waiting,
      coinValue: "0.002BTC", time: "1:23 PM"),
  TradeModel(buyerName: AppImages.johnDoe,
      type: "sell", status: AppStrings.waiting,
      coinValue: "0.002BTC", time: "1:23 PM"),
  TradeModel(buyerName: AppImages.emmanuelPraise,
      type: "trade", status: AppStrings.waiting,
      coinValue: "0.002BTC", time: "1:23 PM"),
  TradeModel(buyerName: AppImages.emmanuelPraise,
      type: "sell", status: AppStrings.waiting,
      coinValue: "0.002BTC", time: "1:23 PM"),
  TradeModel(buyerName: AppImages.johnDoe,
      type: "trade", status: AppStrings.waiting,
      coinValue: "0.002BTC", time: "1:23 PM"),
];