
import 'package:evs_pay_mobile/resources/image_manager.dart';
import 'package:evs_pay_mobile/resources/strings_manager.dart';

class TransactionHistory{
  final String iconName;
  final String status;
  final String coinValue;
  final String time;
  final String type;

  TransactionHistory({
    required this.iconName,
    required this.status,
    required this.coinValue,
    required this.time,
    required this.type,
});

}

final List<TransactionHistory> transactionHistories = [
  TransactionHistory(iconName: AppImages.bitCoinIcon,
      type: "withdraw", status: AppStrings.waiting,
      coinValue: "0.002BTC", time: "1:23 PM"),
  TransactionHistory(iconName: AppImages.bitCoinIcon,
      type: "send", status: AppStrings.waiting,
      coinValue: "0.002BTC", time: "1:23 PM"),
  TransactionHistory(iconName: AppImages.bitCoinIcon,
      type: "withdraw", status: AppStrings.waiting,
      coinValue: "0.002BTC", time: "1:23 PM"),
  TransactionHistory(iconName: AppImages.bitCoinIcon,
      type: "withdraw", status: AppStrings.waiting,
      coinValue: "0.002BTC", time: "1:23 PM"),
  TransactionHistory(iconName: AppImages.bitCoinIcon,
      type: "withdraw", status: AppStrings.waiting,
      coinValue: "0.002BTC", time: "1:23 PM"),
  TransactionHistory(iconName: AppImages.bitCoinIcon,
      type: "withdraw", status: AppStrings.waiting,
      coinValue: "0.002BTC", time: "1:23 PM"),
  TransactionHistory(iconName: AppImages.bitCoinIcon,
      type: "withdraw", status: AppStrings.waiting,
      coinValue: "0.002BTC", time: "1:23 PM"),
  TransactionHistory(iconName: AppImages.bitCoinIcon,
      type: "send", status: AppStrings.waiting,
      coinValue: "0.002BTC", time: "1:23 PM"),
  TransactionHistory(iconName: AppImages.bitCoinIcon,
      type: "send", status: AppStrings.waiting,
      coinValue: "0.002BTC", time: "1:23 PM"),
  TransactionHistory(iconName: AppImages.bitCoinIcon,
      type: "send", status: AppStrings.waiting,
      coinValue: "0.002BTC", time: "1:23 PM"),
  TransactionHistory(iconName: AppImages.bitCoinIcon,
      type: "withdraw", status: AppStrings.waiting,
      coinValue: "0.002BTC", time: "1:23 PM"),
  TransactionHistory(iconName: AppImages.bitCoinIcon,
      type: "withdraw", status: AppStrings.waiting,
      coinValue: "0.002BTC", time: "1:23 PM"),
  TransactionHistory(iconName: AppImages.bitCoinIcon,
      type: "withdraw", status: AppStrings.waiting,
      coinValue: "0.002BTC", time: "1:23 PM"),
  TransactionHistory(iconName: AppImages.bitCoinIcon,
      type: "withdraw", status: AppStrings.waiting,
      coinValue: "0.002BTC", time: "1:23 PM"),
  TransactionHistory(iconName: AppImages.bitCoinIcon,
      type: "withdraw", status: AppStrings.waiting,
      coinValue: "0.002BTC", time: "1:23 PM"),
  TransactionHistory(iconName: AppImages.bitCoinIcon,
      type: "send", status: AppStrings.waiting,
      coinValue: "0.002BTC", time: "1:23 PM"),
  TransactionHistory(iconName: AppImages.bitCoinIcon,
      type: "send", status: AppStrings.waiting,
      coinValue: "0.002BTC", time: "1:23 PM"),
  TransactionHistory(iconName: AppImages.bitCoinIcon,
      type: "withdraw", status: AppStrings.waiting,
      coinValue: "0.002BTC", time: "1:23 PM"),
  TransactionHistory(iconName: AppImages.bitCoinIcon,
      type: "withdraw", status: AppStrings.waiting,
      coinValue: "0.002BTC", time: "1:23 PM"),
  TransactionHistory(iconName: AppImages.bitCoinIcon,
      type: "withdraw", status: AppStrings.waiting,
      coinValue: "0.002BTC", time: "1:23 PM"),
  TransactionHistory(iconName: AppImages.bitCoinIcon,
      type: "withdraw", status: AppStrings.waiting,
      coinValue: "0.002BTC", time: "1:23 PM"),
  TransactionHistory(iconName: AppImages.bitCoinIcon,
      type: "withdraw", status: AppStrings.waiting,
      coinValue: "0.002BTC", time: "1:23 PM"),
  TransactionHistory(iconName: AppImages.bitCoinIcon,
      type: "withdraw", status: AppStrings.waiting,
      coinValue: "0.002BTC", time: "1:23 PM"),
  TransactionHistory(iconName: AppImages.bitCoinIcon,
      type: "withdraw", status: AppStrings.waiting,
      coinValue: "0.002BTC", time: "1:23 PM"),
  TransactionHistory(iconName: AppImages.bitCoinIcon,
      type: "withdraw", status: AppStrings.waiting,
      coinValue: "0.002BTC", time: "1:23 PM"),
  TransactionHistory(iconName: AppImages.bitCoinIcon,
      type: "trade", status: AppStrings.waiting,
      coinValue: "0.002BTC", time: "1:23 PM"),
  TransactionHistory(iconName: AppImages.bitCoinIcon,
      type: "withdraw", status: AppStrings.waiting,
      coinValue: "0.002BTC", time: "1:23 PM"),
  TransactionHistory(iconName: AppImages.bitCoinIcon,
      type: "trade", status: AppStrings.waiting,
      coinValue: "0.002BTC", time: "1:23 PM"),
];